In [12]:
import pandas as pd
import numpy as np
import pickle
import os
import json
import collections
import time


from typing import List, Dict, NoReturn, Union, Any, Optional, Tuple
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.metrics import accuracy_score
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report,accuracy_score, balanced_accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.decomposition import PCA
from imblearn.over_sampling import SMOTENC, ADASYN, RandomOverSampler
from sklearn.utils import resample

In [13]:
df_one_hot_vectors = pd.read_csv('dataset_transformed_1mln_REDUCED.csv',
             sep='\t',
             nrows=50000,
             skiprows=range(1,50000),
             low_memory=True)

In [14]:
df_one_hot_vectors[:3]

Sale  SalesAmountInEuro  click_timestamp  device_type_-1  \
0     1           25.00000       1596458423               0   
1     0           -1.00000       1596458423               0   
2     1           88.89265       1596458424               0   

   device_type_0C297EB7365042A7DCB803298164359F  \
0                                             0   
1                                             0   
2                                             0   

   device_type_1D2373C2A02F5A307C1F0C697ECF8429  \
0                                             0   
1                                             0   
2                                             0   

   device_type_7E56C27BFF0305E788DA55A029EC4988  \
0                                             0   
1                                             0   
2                                             0   

   device_type_B432A885981287B47E08B41E802860B2  \
0                                             0   
1                                             0   
2                                             0   

   device_type_C1ED32BB62670069B0ACE459169A7EAA  \
0                                             0   
1                                             0   
2                                             0   

   device_type_D5AF1EAB7526F8539A66F715079AB628  ...  \
0                                             0  ...   
1                                             0  ...   
2                                             0  ...   

   product_gender_4E0E101FFE4550D92B5CCDEF67A1FE17  \
0                                                0   
1                                                0   
2                                                0   

   product_gender_6EFABCEDA36A931DBF760F88970BAF0E  \
0                                                0   
1                                                0   
2                                                0   

   product_gender_86E2AFBF909EC95B069893FF0BBC5B26  \
0                                                0   
1                                                0   
2                                                0   

   product_gender_8CE4C5DDEE22BB8EE50CF418ED81591C  \
0                                                0   
1                                                0   
2                                                0   

   product_gender_A5D15FC386510762EC0DDFF54ABE6F94  \
0                                                0   
1                                                0   
2                                                0   

   product_gender_C45A9AC6D102ACAEEDF0D6F78636D84A  \
0                                                0   
1                                                0   
2                                                0   

   product_gender_C83584C67375245584CEBF5DCE5BEE2D  \
0                                                0   
1                                                0   
2                                                0   

   product_gender_D7B42B0C4D807EF1C13F79948743E9DA  \
0                                                0   
1                                                0   
2                                                0   

   product_gender_D894202FD3ABAE0B55F9FAE133412DE5  time_delay_for_conversion  
0                                                0                       1266  
1                                                0                         -1  
2                                                0                      86997  

[3 rows x 4229 columns]

In [15]:

df_one_hot_vectors = df_one_hot_vectors.dropna(axis=0) # usuwanie wierszy, które zawierają null
df_one_hot_vectors.isnull().sum()

Sale                                                0
SalesAmountInEuro                                   0
click_timestamp                                     0
device_type_-1                                      0
device_type_0C297EB7365042A7DCB803298164359F        0
device_type_1D2373C2A02F5A307C1F0C697ECF8429        0
device_type_7E56C27BFF0305E788DA55A029EC4988        0
device_type_B432A885981287B47E08B41E802860B2        0
device_type_C1ED32BB62670069B0ACE459169A7EAA        0
device_type_D5AF1EAB7526F8539A66F715079AB628        0
device_type_D7D1FB49049702BF6338894757E0D959        0
device_type_FF2C446555E3822B0E0FC3406116E86D        0
nb_clicks_1week                                     0
partner_id_017EBBBE0B84EC3065F8A4FAFA39A4B2         0
partner_id_01E57DAC509AE48685D6219DE7718BA8         0
partner_id_0225D81C97298F6FD63C8868EE8E2228         0
partner_id_023E892E813B16691CB0F136B92FD92E         0
partner_id_02D9DA79F8E9754EA6E17E1A22636023         0
partner_id_0403781144C992FB9

In [16]:
X = df_one_hot_vectors.iloc[:, 3:].values
y = df_one_hot_vectors.iloc[:, :1].values.ravel()  # tutaj powinny być chyba 3 kolumny

# class_weights = compute_class_weight('balanced',
#                      np.unique(y),
#                      y)
# class_weight_dictionary = {0:class_weights[0], 1:class_weights[1]}

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)

pca = PCA(n_components=500, random_state=1)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)


# start = time.time()
# smote_nc = SMOTENC(categorical_features=list(np.arange(0,96)),random_state=1, n_jobs=-1) 
# x_train, y_train = smote_nc.fit_resample(x_train, y_train)
# end = time.time()
# print(end - start)


adasyn = ADASYN(random_state=1)
x_train, y_train = adasyn.fit_resample(x_train, y_train)

# ros = RandomOverSampler(random_state=1)
# x_train, y_train = ros.fit_sample(x_train, y_train)
    
# x_train = np.vstack((x_train[y_train==0], x_train))
# y_train = np.hstack((y_train[y_train==0], y_train))
# x_sampled, y_sampled = resample(X[y==1],
#                                y[y==1],
#                                replace=True,
#                                n_samples =X[y==0].shape[0],
#                                random_state=1)

In [17]:
print('Liczba etykiet w zbiorze y:', np.bincount(y))
print('Liczba etykiet w zbiorze y_train:', np.bincount(y_train))
print('Liczba etykiet w zbiorze y_test:', np.bincount(y_test))

# lr = make_pipeline(StandardScaler(),
# #                        PCA(n_components=100),
#                         SGDClassifier(loss='log', verbose=0, n_jobs=-1, random_state=1, tol=1e-3, max_iter=1000, class_weight='balanced'))

# lr = SGDClassifier(loss='log', verbose=0, n_jobs=-1, random_state=1, tol=1e-3, max_iter=1000, penalty='l2')#, class_weight=class_weight_dictionary)
lr = SGDClassifier(loss='log', random_state=1, tol=1e-3, max_iter=1000, penalty='l1', alpha=1e-05)

sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_train_std = normalize(x_train_std, norm='l2')
x_test_std = sc.transform(x_test)
x_test_std = normalize(x_test_std, norm='l2')

Liczba etykiet w zbiorze y: [42756  7244]
Liczba etykiet w zbiorze y_train: [34205 34198]
Liczba etykiet w zbiorze y_test: [8551 1449]


In [18]:
# start = time.time()
# scores = cross_val_score(estimator=lr,
#                         X=x_train_std,
#                         y=y_train,
#                         cv=10,
#                         n_jobs=1)
# end = time.time()
# print(end-start)
# print(scores)
# print('Dokładność sprawdzianu: %.3f +/- %.3f' % (np.mean(scores), np.std(scores)))

start = time.time()
lr.fit(x_train_std, y_train)
end = time.time()
print("Czas treningu: {0}".format((end-start)))
print("LOG: creating model DONE")

print(collections.Counter(y_test))
y_pred = lr.predict(x_test_std)
print(collections.Counter(y_pred))

print("LOG: testing model DONE")
print('balanced_accuracy_score: {0}'.format(balanced_accuracy_score(y_test, y_pred)))
print('accuracy_score: {0}'.format(accuracy_score(y_test, y_pred)))

print('Nieprawidłowo sklasyfikowane próbki: %d' % (y_test != y_pred).sum())

print('classification_report :\n',classification_report(y_test,y_pred))
confmat = confusion_matrix(y_true=y_test, y_pred=y_pred)
print(confmat)

Czas treningu: 5.189800024032593
LOG: creating model DONE
Counter({0: 8551, 1: 1449})
Counter({0: 8752, 1: 1248})
LOG: testing model DONE
balanced_accuracy_score: 0.6973967101462996
accuracy_score: 0.8643
Nieprawidłowo sklasyfikowane próbki: 1357
classification_report :
               precision    recall  f1-score   support

           0       0.91      0.93      0.92      8551
           1       0.54      0.46      0.50      1449

    accuracy                           0.86     10000
   macro avg       0.72      0.70      0.71     10000
weighted avg       0.86      0.86      0.86     10000

[[7973  578]
 [ 779  670]]


In [ ]:
from sklearn.model_selection import validation_curve, learning_curve
import matplotlib.pyplot as plt

param_range = [1e-15,1e-14,1e-13,1e-12,1e-11,1e-10,1e-9,1e-8,1e-7]
train_scores, test_scores = validation_curve(
                estimator=lr, 
                X=x_train_std, 
                y=y_train, 
                param_name='alpha', 
                param_range=param_range,
                cv=10)

train_mean = np.mean(train_scores, axis=1)
train_std = np.std(train_scores, axis=1)
test_mean = np.mean(test_scores, axis=1)
test_std = np.std(test_scores, axis=1)

plt.plot(param_range, train_mean, 
         color='blue', marker='o', 
         markersize=5, label='Dokładność uczenia')

plt.fill_between(param_range, train_mean + train_std,
                 train_mean - train_std, alpha=0.15,
                 color='blue')

plt.plot(param_range, test_mean, 
         color='green', linestyle='--', 
         marker='s', markersize=5, 
         label='Dokładność walidacji')

plt.fill_between(param_range, 
                 test_mean + test_std,
                 test_mean - test_std, 
                 alpha=0.15, color='green')

plt.grid()
plt.xscale('log')
plt.legend(loc='lower right')
plt.xlabel('Parametr C')
plt.ylabel('Dokładność')
plt.ylim([0.4, 0.8])
plt.tight_layout()
#plt.savefig('rysunki/06_06.png', dpi=300)
plt.show()

In [ ]:
plt.plot(param_range, train_mean, 
         color='blue', marker='o', 
         markersize=5, label='Dokładność uczenia')

plt.fill_between(param_range, train_mean + train_std,
                 train_mean - train_std, alpha=0.15,
                 color='blue')

plt.plot(param_range, test_mean, 
         color='green', linestyle='--', 
         marker='s', markersize=5, 
         label='Dokładność walidacji')

plt.fill_between(param_range, 
                 test_mean + test_std,
                 test_mean - test_std, 
                 alpha=0.15, color='green')

plt.grid()
plt.xscale('log')
plt.legend(loc='lower right')
plt.xlabel('Parametr C')
plt.ylabel('Dokładność')
plt.ylim([0.4, 0.8])
plt.tight_layout()
#plt.savefig('rysunki/06_06.png', dpi=300)
plt.show()

In [ ]:
# compute_class_weight('balanced', np.unique(y), y)

In [ ]:
# save the model to disk
pickle.dump(lr, open('model.sav', 'wb'))
pickle.dump(sc, open('standard_scaler.sav', 'wb'))

In [ ]:
# load the model from disk
lr = pickle.load(open('model.sav', 'rb'))
sc = pickle.load(open('standard_scaler.sav', 'rb'))

In [ ]:
df_one_hot_vectors = pd.read_csv('dataset_transformed_1mln_REDUCED.csv',
             sep='\t',
             nrows=50000,
             skiprows=range(1,150000),
             header=0,
             low_memory=True)

In [ ]:
x = df_one_hot_vectors.iloc[:, 3:].values
y = df_one_hot_vectors['Sale'].values.ravel()

x_sampled, y_sampled = resample(x[y==1],
                               y[y==1],
                               replace=True,
                               n_samples =x[y==0].shape[0],
                               random_state=1)

x = np.vstack((x[y==0], x_sampled))
y = np.hstack((y[y==0], y_sampled))


x = sc.transform(x)
x = normalize(x, norm='l2')
y = np.array([int(i) for i in y])
lr.partial_fit(x, y, classes=np.array([0, 1]))

In [ ]:
# save the model to disk
pickle.dump(lr, open('model2.sav', 'wb'))
pickle.dump(sc, open('standard_scaler2.sav', 'wb'))

In [ ]:
# load the model from disk
lr = pickle.load(open('model2.sav', 'rb'))
sc = pickle.load(open('standard_scaler2.sav', 'rb'))

In [ ]:
df_one_hot_vectors_test = pd.read_csv('dataset_transformed_1mln_REDUCED.csv',
             sep='\t',
             nrows=50000,
#              skiprows=range(1,50000),
             low_memory=True)

In [ ]:
x_test = df_one_hot_vectors_test.iloc[:, 3:].values
y_test = df_one_hot_vectors_test.iloc[:, :1].values.ravel()  # tutaj powinny być chyba 3 kolumny

x_test_std = sc.transform(x_test)
x_test_std = normalize(x_test_std, norm='l2')

print(collections.Counter(y_test))
y_pred = lr.predict(x_test_std)
print(collections.Counter(y_pred))

In [ ]:
print(accuracy_score(y_test, y_pred))
print('Nieprawidłowo sklasyfikowane próbki: %d' % (y_test != y_pred).sum())
print('Dokładność: %.2f' % lr.score(x_test_std, y_test))

In [ ]:
print('Liczba etykiet w zbiorze y:', np.bincount(y_test))

In [ ]:
# print('Nieprawidłowo sklasyfikowane próbki: %d' % (y_test != y_pred).sum())
print('Dokładność: %.2f' % lr.score(x_test_std, y_test))

print('accuracy = ',lr.score(x_test_std, y_test).round(2),
      'precision = ',precision_score(y_test, y_pred).round(2), 
      'recall = ',recall_score(y_test, y_pred).round(2), 
      'f1_score = ',f1_score(y_test, y_pred).round(2))
confmat = confusion_matrix(y_true=y_test, y_pred=y_pred)
print(confmat)

In [20]:
df_one_hot_vectors_test = pd.read_csv('dataset_transformed_1mln_REDUCED.csv',
             sep='\t',
             nrows=50000,
#                  skiprows=range(1,250000),
             low_memory=True)
    
for i in range(20):
    # PREDYKCJA
    print('Iteracja: {0}'.format(i))

    x_test = df_one_hot_vectors_test.iloc[:, 3:].values
    y_test = df_one_hot_vectors_test.iloc[:, :1].values.ravel()  # tutaj powinny być chyba 3 kolumny
    
    x_test = pca.transform(x_test)
    x_test_std = sc.transform(x_test)
    x_test_std = normalize(x_test_std, norm='l2')

    print(collections.Counter(y_test))
    y_pred = lr.predict(x_test_std)
    print(collections.Counter(y_pred))

    print(accuracy_score(y_test, y_pred))
    print('Nieprawidłowo sklasyfikowane próbki: %d' % (y_test != y_pred).sum())
    print('balanced_accuracy_score: {0}'.format(balanced_accuracy_score(y_test, y_pred)))
    print('accuracy_score: {0}'.format(accuracy_score(y_test, y_pred)))
    print('classification_report :\n',classification_report(y_test,y_pred))
    confmat = confusion_matrix(y_true=y_test, y_pred=y_pred)
    print(confmat)
    print('\n')
    
    # NAUKA
    df_one_hot_vectors = pd.read_csv('dataset_transformed_1mln_REDUCED.csv',
                 sep='\t',
                 nrows=50000,
                 skiprows=range(1,100000+50000*i),
                 header=0,
                 low_memory=True)

    
    df_one_hot_vectors = df_one_hot_vectors.dropna(axis=0) # usuwanie wierszy, które zawierają null

    x = df_one_hot_vectors.iloc[:, 3:].values
    y = df_one_hot_vectors['Sale'].values.ravel()
    
    x = pca.transform(x)


#     smote_nc = SMOTENC(categorical_features=list(np.arange(0,4225)), random_state=1)
#     x, y = smote_nc.fit_resample(x, y)

#     adasyn = ADASYN(random_state=1)
    x, y = adasyn.fit_resample(x, y)

#     ros = RandomOverSampler(random_state=1)
#     x, y = ros.fit_sample(x, y)

#     x_sampled, y_sampled = resample(x[y==1],
#                                    y[y==1],
#                                    replace=True,
#                                    n_samples =x[y==0].shape[0],
#                                    random_state=1)

#     x = np.vstack((x[y==0], x_sampled))
#     y = np.hstack((y[y==0], y_sampled))


    x = sc.transform(x)
    x = normalize(x, norm='l2')
    y = np.array([int(i) for i in y])
    lr = lr.partial_fit(x, y, classes=np.array([0, 1]))

Iteracja: 0
Counter({0: 44126, 1: 5874})
Counter({0: 44368, 1: 5632})
0.87692
Nieprawidłowo sklasyfikowane próbki: 6154
balanced_accuracy_score: 0.6942884608876327
accuracy_score: 0.87692
classification_report :
               precision    recall  f1-score   support

           0       0.93      0.93      0.93     44126
           1       0.48      0.46      0.47      5874

    accuracy                           0.88     50000
   macro avg       0.70      0.69      0.70     50000
weighted avg       0.87      0.88      0.88     50000

[[41170  2956]
 [ 3198  2676]]


Iteracja: 1
Counter({0: 44126, 1: 5874})
Counter({0: 44908, 1: 5092})
0.88196
Nieprawidłowo sklasyfikowane próbki: 5902
balanced_accuracy_score: 0.6865182058046516
accuracy_score: 0.88196
classification_report :
               precision    recall  f1-score   support

           0       0.93      0.94      0.93     44126
           1       0.50      0.43      0.46      5874

    accuracy                           0.88     50

[[40266  3860]
 [ 2980  2894]]


Iteracja: 15
Counter({0: 44126, 1: 5874})
Counter({0: 43075, 1: 6925})
0.86254
Nieprawidłowo sklasyfikowane próbki: 6873
balanced_accuracy_score: 0.7073189759581435
accuracy_score: 0.86254
classification_report :
               precision    recall  f1-score   support

           0       0.93      0.91      0.92     44126
           1       0.43      0.50      0.46      5874

    accuracy                           0.86     50000
   macro avg       0.68      0.71      0.69     50000
weighted avg       0.87      0.86      0.87     50000

[[40164  3962]
 [ 2911  2963]]


Iteracja: 16
Counter({0: 44126, 1: 5874})
Counter({0: 44876, 1: 5124})
0.88968
Nieprawidłowo sklasyfikowane próbki: 5516
balanced_accuracy_score: 0.7063140882461653
accuracy_score: 0.88968
classification_report :
               precision    recall  f1-score   support

           0       0.93      0.95      0.94     44126
           1       0.53      0.47      0.50      5874

    accuracy   

In [ ]:
start = time.time()
adasyn = ADASYN(random_state=1)
x_train, y_train = adasyn.fit_resample(x_train, y_train)
end = time.time()
print(end-start)

In [ ]:
from sklearn.model_selection import GridSearchCV

start = time.time()
pipe = make_pipeline(StandardScaler(),
#                      PCA(random_state=1),
#                      ADASYN(random_state=1),
                     SGDClassifier(loss='log', random_state=1, tol=1e-3, max_iter=1000))

param_grid = [{'sgdclassifier__alpha': [1e-15, 1e-10, 1e-5, 0.01], 
               'sgdclassifier__penalty': ['l1', 'l2']
              }]

gs = GridSearchCV(estimator=pipe, 
                  param_grid=param_grid, 
                  scoring= 'balanced_accuracy', 
                  cv=10,
                  n_jobs=-1)
gs = gs.fit(x_train, y_train)
print(gs.best_score_)
print(gs.best_params_)
end = time.time()
print(end-start)

In [ ]:
print(gs.)